### ISSUE TITLE
Cannot open odt saved by LibreOffice7

### ISSUE THREAD

**Issue by nakamura-t0428** [nakamura-t0428/jOpenDocument#3]
When open odt file saved by Libraoffice7.0.x (or later), following errors occur.

```java
new JavaScriptTemplate(getClass().getResourceAsStream(FILEPATH));
```

Sacktrace
```
java.lang.NullPointerException
	at org.jopendocument.dom.ODSingleXMLDocument.getFontDecls(ODSingleXMLDocument.java:849)
	at org.jopendocument.dom.ODSingleXMLDocument.mergeFontDecls(ODSingleXMLDocument.java:844)
	at org.jopendocument.dom.ODSingleXMLDocument.mergeAllStyles(ODSingleXMLDocument.java:674)
	at org.jopendocument.dom.ODSingleXMLDocument.create(ODSingleXMLDocument.java:315)
	at org.jopendocument.dom.ODPackage.toSingle(ODPackage.java:1084)
	at org.jopendocument.dom.template.Template.<init>(Template.java:63)
	at org.jopendocument.dom.template.Template.<init>(Template.java:54)
	at org.jopendocument.dom.template.EngineTemplate.<init>(EngineTemplate.java:34)
	at org.jopendocument.dom.template.JavaScriptTemplate.<init>(JavaScriptTemplate.java:46)
```

**Comment by nakamura-t0428** [comment]
fixed.
https://github.com/nakamura-t0428/jOpenDocument/tree/fix/odt-libreoffice-7
